const items = [
  { id: 1, name: "Margherita Pizza", price: 8.99 },
  { id: 2, name: "Cheeseburger", price: 7.5 },
  { id: 3, name: "Veggie Pasta", price: 8.0 },
  { id: 4, name: "French Fries", price: 3.5 },
  { id: 5, name: "Spaghetti Bolognese", price: 9.5 },
  { id: 6, name: "Fettuccine Alfredo", price: 10.0 },
  { id: 7, name: "Caesar Salad", price: 6.5 },
  { id: 8, name: "Onion Rings", price: 4.0 },
  { id: 9, name: "Chocolate Brownie", price: 3.5 },
  { id: 10, name: "Ice Cream Sundae", price: 3.0 },
  { id: 11, name: "Veggie Burger", price: 7.0 },
  { id: 12, name: "BLT Sandwich", price: 6.5 },
  { id: 13, name: "Chicken Wings (6 pcs)", price: 6.5 },
  { id: 14, name: "Fish and Chips", price: 10.0 },
  { id: 15, name: "Steak (8 oz)", price: 15.0 },
  { id: 16, name: "Pancakes (3 pcs)", price: 5.0 },
  { id: 17, name: "Waffles", price: 5.5 },
  { id: 18, name: "Milkshake (Vanilla)", price: 4.0 },
  { id: 19, name: "Cheesecake", price: 4.5 },
  { id: 20, name: "Taco (Mutton)", price: 4.5 },
  { id: 21, name: "Taco (Chicken)", price: 4.0 },
  { id: 22, name: "Quesadilla", price: 7.0 },
  { id: 23, name: "Nachos", price: 6.5 },
  { id: 24, name: "Chicken Caesar Wrap", price: 7.5 },
  { id: 25, name: "Veggie Wrap", price: 6.5 },
  { id: 26, name: "Paneer Pizza", price: 9.0 },
  { id: 27, name: "Mushroom Soup", price: 5.0 },
  { id: 28, name: "Grilled Salmon", price: 13.5 },
  { id: 29, name: "Pork Ribs", price: 14.0 },
  { id: 30, name: "Mac and Cheese", price: 7.5 },
  { id: 31, name: "Chicken Parmesan", price: 12.0 },
  { id: 32, name: "Grilled Chicken Sandwich", price: 8.5 },
  { id: 33, name: "Garlic Bread", price: 4.0 },
  { id: 34, name: "Mozzarella Sticks", price: 5.0 },
  { id: 35, name: "Buffalo Wings (6 pcs)", price: 7.0 },
  { id: 36, name: "Fruit Salad", price: 4.5 },
  { id: 37, name: "Grilled Cheese Sandwich", price: 5.5 },
  { id: 38, name: "Parmesan Fries", price: 4.0 },
  { id: 39, name: "Veggie Pizza", price: 8.5 },
  { id: 40, name: "Chocolate Milkshake", price: 4.0 }
];

export default items;